# Generated by Django 4.2 on 2024-04-18 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_item_liked_by_item_price_item_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.item')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_items', to='articles.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'item')},
            },
        ),
    ]
