# Generated by Django 4.2 on 2024-04-18 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_likeditem'),
    ]

    operations = [
    ]
