# Generated by Django 4.2 on 2024-04-18 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20240418_1935'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikedItem',
        ),
    ]
