# Generated by Django 4.2 on 2024-04-18 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0009_likeditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_items', through='articles.LikedItem', to=settings.AUTH_USER_MODEL),
        ),
    ]
