# Generated by Django 4.2 on 2024-04-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_item_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
